=== oicr-gsi/djerba/src/lib/djerba/data/input_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/oicr-gsi/djerba/blob/master/src/lib/djerba/data/input_schema.json",
    "type": "object",
    "properties":
    {
	"study_meta": {
	    "type": "object",
	    "properties": {
		"add_global_case_list": {"type": "boolean"},
		"cancer_study_identifier": {"type": "string"},
		"citation": {"type": ["string", "null"]},
		"description": {"type": "string"},
		"groups": {"type": ["string", "null"]},
		"name": {"type": "string"},
		"pmid": {"type": ["string", "null"]},
		"reference_genome": {"type": ["string", "null"]},
		"short_name": {"type": "string"},
		"tags_file": {"type": ["string", "null"]},
		"type_of_cancer": {"type": "string"}
	    },
	    "required": [
		"add_global_case_list",
		"cancer_study_identifier",
		"citation",
		"description",
		"groups",
		"name",
		"pmid",
		"reference_genome",
		"short_name",
		"tags_file",
		"type_of_cancer"
	    ]
	},
	"cancer_type": {
	    "type": "object",
	    "properties": {
		"clinical_trial_keywords": {
		    "type": "array",
		    "items": {"type": "string"}
		},
		"data_filename": {"type": "string"},
		"dedicated_color": {"type": ["string", "null"]},
		"name": {
		    "type": "array",
		    "items": {"type": "string"}
		},
		"parent_type_of_cancer": {
		    "type": "array",
		    "items": {"type": "string"}
		},
		"type_of_cancer": {"type": ["string", "null"]}
	    },
	    "required": [
		"clinical_trial_keywords",
		"data_filename",
		"dedicated_color",
		"name",
		"parent_type_of_cancer",
		"type_of_cancer"
	    ]
	},
	"case_lists": {
	    "type": "array",
	    "items": {
		"type": "object",
		"properties": {
		    "case_list_category": {"type": ["string", "null"]},
		    "case_list_description": {"type": "string"},
		    "case_list_ids": {
			"type": "array",
			"items": {"type": "string"}
		    },
		    "case_list_name": {"type": "string"},
		    "suffix": {"type": "string"}
		},
		"required": [
		    "case_list_category",
		    "case_list_description",
		    "case_list_ids",
		    "case_list_name"
		]
	    }
	},
	"samples_meta": {
	    "type": "object",
	    "properties": {
		"attribute_names":  {
		    "type": "array",
		    "items": {"type": "string"}
		},
		"datatypes":  {
		    "type": "array",
		    "items": {"type": "string"}
		},
		"descriptions":  {
		    "type": "array",
		    "items": {"type": "string"}
		},
		"display_names":  {
		    "type": "array",
		    "items": {"type": "string"}
		},
		"precision": {"type": "integer"},
		"priorities":  {
		    "type": "array",
		    "items": {"type": "integer"}
		},
		"write_patients":  {"type": "boolean"}
	    },
	    "required": [
		"attribute_names",
		"datatypes",
		"descriptions",
		"display_names",
		"precision",
		"priorities",
		"write_patients"
	    ]
	},
	"samples": {
	    "type": "array",
	    "items": {
		"type": "object",
		"properties": {
		    "SAMPLE_ID": {"type": "string"},
		    "COSMIC_SIGS": {"type": ["string", "null"]},
		    "CANCER_TYPE": {"type": ["string", "null"]},
		    "CANCER_TYPE_DETAILED": {"type": ["string", "null"]},
		    "CLOSEST_TCGA": {"type": ["string", "null"]},
		    "SAMPLE_ANATOMICAL_SITE": {"type": ["string", "null"]},
		    "SAMPLE_PRIMARY_OR_METASTASIS": {"type": ["string", "null"]},
		    "TREATMENT_STATUS": {"type": ["string", "null"]},
		    "PATHOLOGICAL_REVIEW": {"type": ["string", "null"]},
		    "MEAN_COVERAGE": {"type": ["integer", "null"]},
		    "PCT_v7_ABOVE_80x": {"type": ["number", "null"]},
		    "FRAC_CALLABILITY": {"type": ["number", "null"]},
		    "SEQUENZA_PURITY_FRACTION": {"type": ["integer", "null"]},
		    "SEQUENZA_PLOIDY": {"type": ["integer", "null"]},
		    "TMB_PER_MB": {"type": ["number", "null"]},
		    "HRD_SCORE": {"type": ["string", "null"]},
		    "MSI_STATUS": {"type": ["string", "null"]},
		    "SEX": {"type": ["string", "null"]},
		    "AGE": {"type": ["integer", "null"]},
		    "PATIENT_ID": {"type": ["string", "null"]},
		    "CENTRE": {"type": ["string", "null"]},
		    "FRACTION_GENOME_ALTERED": {"type": ["number", "null"]},
		    "TMB_PLOT": {"type": ["string", "null"]},
		    "VAF_PLOT": {"type": ["string", "null"]},
		    "ETHNICITY": {"type": ["string", "null"]}
		},
		"required": ["SAMPLE_ID"],
		"uniqueItems": true
	    }
	},
	"genetic_alterations": {
	    "type": "array",
	    "items": {
		"type": "object",
		"properties": {
		    "datatype": {
			"type": "string"
		    },
		    "genetic_alteration_type": {
			"type": "string"
		    },
		    "input_directory": {
			"type": "string"
		    },
		    "workflow_run_id": {
			"type": "string"
		    },
		    "input_files": {
			"type": "object"
		    },
		    "metadata": {
			"type": "object"
		    }
		},
		"required": [
		    "datatype", "genetic_alteration_type", "input_directory", "input_files", "metadata"
		],
		"uniqueItems": true
	    }
	}
    },
    "required": [
	"samples",
	"genetic_alterations"
    ],
    "dependencies": {
	"study_meta": ["cancer_type", "case_lists", "samples_meta"],
	"cancer_type": ["study_meta", "case_lists", "samples_meta"],
	"case_lists": ["study_meta", "cancer_type", "samples_meta"],
	"samples_meta": ["study_meta", "cancer_type", "case_lists"]
    }
}

=== oicr-gsi/djerba/src/test/data/study_config_mx.json
{
    "cancer_type": {
        "clinical_trial_keywords": [
            "carcinoma,ductal carcinoma"
        ],
        "data_filename": "cancer_type.txt",
        "dedicated_color": null,
        "name": [
            "Ductal Carcinoma"
        ],
        "parent_type_of_cancer": [
            "tissue"
        ],
        "type_of_cancer": null
    },
    "case_lists": [
        {
            "case_list_category": null,
            "case_list_description": "custom case list demonstration",
            "case_list_ids": [
                "OCT-01-0472-CAP"
            ],
            "case_list_name": "djerba_custom_case_list",
            "suffix": "custom"
        }
    ],
    "genetic_alterations": [
        {
            "datatype": "MAF",
            "genetic_alteration_type": "MUTATION_EXTENDED",
            "input_files": {
                "OCT-01-0472-CAP": "somatic01.maf.txt.gz"
            },
            "input_directory": "/.mounts/labs/gsiprojects/gsi/djerba/mutation_extended",
            "metadata": {
                "filter_vcf": "/.mounts/labs/gsiprojects/gsi/cBioGSI/data/reference/ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz",
                "oncokb_api_token": "e326982a-02ba-4f04-8ef6-80b04fa74acd",
                "profile_description": "Dummy profile for Djerba test",
                "profile_name": "Djerba test 001",
                "bed_path": "/.mounts/labs/gsiprojects/gsi/djerba/prototypes/tmb/S31285117_Regions.bed",
                "tcga_path": "/.mounts/labs/gsiprojects/gsi/djerba/prototypes/tmb/tcga_tmbs.txt",
                "cancer_type": "blca"
            },
            "workflow_run_id": "jabberwocky_workflow_run_0001"
        }
    ],
    "samples": [
        {
            "AGE": 35,
            "CANCER_TYPE": "Bowel",
            "CANCER_TYPE_DETAILED": "MACR",
            "CENTRE": "TGL",
            "CLOSEST_TCGA": "coadread",
            "COSMIC_SIGS": null,
            "ETHNICITY": "Other",
            "FGA": null,
            "FRAC_CALLABILITY": null,
            "MEAN_COVERAGE": null,
            "PATHOLOGICAL_REVIEW": "Lots of immune cells",
            "PATIENT_ID": "OCT-01-0472",
            "PATIENT_SUMMARY": "Nulla a scelerisque ipsum. Aliquam erat volutpat in.",
            "PCT_v7_ABOVE_80x": null,
            "SAMPLE_ANATOMICAL_SITE": "OMENTUM",
            "SAMPLE_ID": "OCT-01-0472-CAP",
            "SAMPLE_PRIMARY_OR_METASTASIS": "Metastatic Lesion",
            "SEQUENZA_PLOIDY": null,
            "SEQUENZA_PURITY_FRACTION": null,
            "SEX": "Male",
            "TMB_PER_MB": null,
            "TREATMENT_STATUS": "Naive"
        }
    ],
    "samples_meta": {
        "attribute_names": [
            "PATIENT_ID",
            "SAMPLE_ID"
        ],
        "datatypes": [
            "STRING",
            "STRING"
        ],
        "descriptions": [
            "Patient identifier",
            "Sample identifier"
        ],
        "display_names": [
            "Patient identifier",
            "Sample identifier"
        ],
        "precision": 3,
        "priorities": [
            1,
            1
        ],
        "write_patients": true
    },
    "study_meta": {
        "add_global_case_list": true,
        "cancer_study_identifier": "djerba_test_001",
        "citation": null,
        "description": "Test of Djerba software package (September 2020)",
        "groups": null,
        "name": "Djerba Test 001",
        "pmid": null,
        "reference_genome": null,
        "short_name": "Djerba 001",
        "tags_file": null,
        "type_of_cancer": "ductal carcinoma"
    }
}

=== oicr-gsi/djerba/src/test/data/report_config_seg.json
{
    "cancer_type": {
        "clinical_trial_keywords": [
            "carcinoma,ductal carcinoma"
        ],
        "data_filename": "cancer_type.txt",
        "dedicated_color": null,
        "name": [
            "Ductal Carcinoma"
        ],
        "parent_type_of_cancer": [
            "tissue"
        ],
        "type_of_cancer": null
    },
    "case_lists": [
        {
            "case_list_category": null,
            "case_list_description": "custom case list demonstration",
            "case_list_ids": [
                "OCT-01-0472-CAP"
            ],
            "case_list_name": "djerba_custom_case_list",
            "suffix": "custom"
        }
    ],
    "genetic_alterations": [
        {
            "datatype": "CUSTOM",
            "genetic_alteration_type": "CUSTOM_ANNOTATION",
            "input_files": {},
            "input_directory": "/dummy/directory/replaced/in/test",
            "metadata": {
                "gene_headers": [
                    "Gene",
                    "Allele_Fraction_Percentile",
                    "Chromosome",
                    "Copy_State",
                    "Drug_Annotation",
                    "Exp_Percentile",
                    "Exp_Z_Score",
                    "FDA_Approved_Treatment",
                    "Gene_Annotation",
                    "OncoKB",
                    "Oncogenic_Binary",
                    "Protein_Change",
                    "Variant_Reads_And_Total_Reads",
                    "Whizbam_URL",
                    "Fusion",
                    "Mutation_Class",
                    "Variant_Classification"
                ],
                "gene_tsv": "custom_gene_annotation.tsv",
                "sample_headers": [
                    "SAMPLE_ID",
                    "AGE",
                    "CANCER_TYPE",
                    "CANCER_TYPE_DETAILED",
                    "CENTRE",
                    "CLOSEST_TCGA",
                    "COSMIC_SIGS",
                    "DATE_REPORT",
                    "DATE_SAMPLE_RECEIVED",
                    "ETHNICITY",
                    "FRACTION_GENOME_ALTERED",
                    "FRAC_CALLABILITY",
                    "HRD_SCORE",
                    "MEAN_COVERAGE",
                    "MSI_STATUS",
                    "ORDERING_PHYSICIAN",
                    "PATHOLOGICAL_REVIEW",
                    "PATIENT_ID",
                    "PATIENT_SUMMARY",
                    "PCT_v7_ABOVE_80x",
                    "REPORT_IDENTIFIER",
                    "SAMPLE_ANATOMICAL_SITE",
                    "SAMPLE_PRIMARY_OR_METASTASIS",
                    "SAMPLE_TYPE",
                    "SEQUENZA_PLOIDY",
                    "SEQUENZA_PURITY_FRACTION",
                    "SEX",
                    "TCGA_PERCENTILE_ALL",
                    "TCGA_PERCENTILE_COHORT",
                    "TMB_PER_MB",
                    "TMB_PLOT",
                    "TREATMENT_STATUS",
                    "VAF_PLOT"
                ],
                "sample_tsv": "custom_sample_annotation.tsv"
            },
            "workflow_run_id": "jabberwocky_workflow_run_0001"
        },
        {
            "datatype": "MAF",
            "genetic_alteration_type": "MUTATION_EXTENDED",
            "input_files": {
                "OCT-01-0472-CAP": "somatic01.maf.txt.gz"
            },
            "input_directory": "/.mounts/labs/gsiprojects/gsi/djerba/mutation_extended",
            "metadata": {
                "filter_vcf": "/.mounts/labs/gsiprojects/gsi/cBioGSI/data/reference/ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz",
                "oncokb_api_token": "e326982a-02ba-4f04-8ef6-80b04fa74acd",
                "profile_description": "Dummy profile for Djerba test",
                "profile_name": "Djerba test 001",
                "bed_path": "/.mounts/labs/gsiprojects/gsi/djerba/prototypes/tmb/S31285117_Regions.bed",
                "tcga_path": "/.mounts/labs/gsiprojects/gsi/djerba/prototypes/tmb/tcga_tmbs.txt",
                "cancer_type": "blca"
            },
            "workflow_run_id": "jabberwocky_workflow_run_0001"
        },
	{
            "datatype": "SEG",
            "genetic_alteration_type": "SEGMENTED",
            "input_files": {
                "OCT-01-0472-CAP": "OCT-01-0472-CAP.tumour.bam.varscanSomatic_Total_CN.seg"
            },
            "input_directory": "/.mounts/labs/gsiprojects/gsi/djerba/segmented",
            "metadata": {
            },
            "workflow_run_id": "sequenza_workflow_run_0001"
        }
    ],
    "samples": [
        {
            "AGE": 35,
            "CANCER_TYPE": "Bowel",
            "CANCER_TYPE_DETAILED": "MACR",
            "CENTRE": "TGL",
            "CLOSEST_TCGA": "coadread",
            "COSMIC_SIGS": null,
            "ETHNICITY": "Other",
            "FRAC_CALLABILITY": null,
            "MEAN_COVERAGE": null,
            "PATHOLOGICAL_REVIEW": "Lots of immune cells",
            "PATIENT_ID": "OCT-01-0472",
            "PATIENT_SUMMARY": "Nulla a scelerisque ipsum. Aliquam erat volutpat in.",
            "PCT_v7_ABOVE_80x": null,
            "SAMPLE_ANATOMICAL_SITE": "OMENTUM",
            "SAMPLE_ID": "OCT-01-0472-CAP",
            "SAMPLE_PRIMARY_OR_METASTASIS": "Metastatic Lesion",
            "SEQUENZA_PLOIDY": null,
            "SEQUENZA_PURITY_FRACTION": null,
            "SEX": "Male",
            "TMB_PER_MB": null,
            "TREATMENT_STATUS": "Naive"
        }
    ],
    "samples_meta": {
        "attribute_names": [
            "PATIENT_ID",
            "SAMPLE_ID"
        ],
        "datatypes": [
            "STRING",
            "STRING"
        ],
        "descriptions": [
            "Patient identifier",
            "Sample identifier"
        ],
        "display_names": [
            "Patient identifier",
            "Sample identifier"
        ],
        "precision": 3,
        "priorities": [
            1,
            1
        ],
        "write_patients": true
    },
    "study_meta": {
        "add_global_case_list": true,
        "cancer_study_identifier": "djerba_test_001",
        "citation": null,
        "description": "Test of Djerba software package (September 2020)",
        "groups": null,
        "name": "Djerba Test 001",
        "pmid": null,
        "reference_genome": null,
        "short_name": "Djerba 001",
        "tags_file": null,
        "type_of_cancer": "ductal carcinoma"
    }
}

=== oicr-gsi/djerba/src/test/data/report_config_custom.json
{
    "cancer_type": {
        "clinical_trial_keywords": [
            "carcinoma,ductal carcinoma"
        ],
        "data_filename": "cancer_type.txt",
        "dedicated_color": null,
        "name": [
            "Ductal Carcinoma"
        ],
        "parent_type_of_cancer": [
            "tissue"
        ],
        "type_of_cancer": null
    },
    "case_lists": [
        {
            "case_list_category": null,
            "case_list_description": "custom case list demonstration",
            "case_list_ids": [
                "OCT-01-0472-CAP"
            ],
            "case_list_name": "djerba_custom_case_list",
            "suffix": "custom"
        }
    ],
    "genetic_alterations": [
        {
            "datatype": "CUSTOM",
            "genetic_alteration_type": "CUSTOM_ANNOTATION",
            "input_files": {},
	    "input_directory": "/dummy/directory/replaced/in/test",
            "metadata": {
		"gene_headers": ["Gene", "Gene_metric_1", "Gene_metric_2", "Gene_metric_3"],
		"gene_tsv": "custom_gene_annotation.tsv",
		"sample_headers": ["SAMPLE_ID", "SAMPLE_METRIC_1", "SAMPLE_METRIC_2", "SAMPLE_METRIC_3"],
		"sample_tsv": "custom_sample_annotation.tsv"
            },
            "workflow_run_id": "jabberwocky_workflow_run_0001"
        }
    ],
    "samples": [
        {
            "AGE": 35,
            "CANCER_TYPE": "Bowel",
            "CANCER_TYPE_DETAILED": "MACR",
            "CENTRE": "TGL",
            "CLOSEST_TCGA": "coadread",
            "COSMIC_SIGS": null,
            "ETHNICITY": "Other",
            "FGA": null,
            "FRAC_CALLABILITY": null,
            "MEAN_COVERAGE": null,
            "PATHOLOGICAL_REVIEW": "Lots of immune cells",
            "PATIENT_ID": "OCT-01-0472",
            "PCT_v7_ABOVE_80x": null,
            "SAMPLE_ANATOMICAL_SITE": "OMENTUM",
            "SAMPLE_ID": "OCT-01-0472-CAP",
            "SAMPLE_PRIMARY_OR_METASTASIS": "Metastatic Lesion",
            "SEQUENZA_PLOIDY": null,
            "SEQUENZA_PURITY_FRACTION": null,
            "SEX": "Male",
	    "TMB_PER_MB":  null,
            "TREATMENT_STATUS": "Naive"
        }
    ],
    "samples_meta": {
        "attribute_names": [
            "PATIENT_ID",
            "SAMPLE_ID"
        ],
        "datatypes": [
            "STRING",
            "STRING"
        ],
        "descriptions": [
            "Patient identifier",
            "Sample identifier"
        ],
        "display_names": [
            "Patient identifier",
            "Sample identifier"
        ],
        "precision": 3,
        "priorities": [
            1,
            1
        ],
        "write_patients": true
    },
    "study_meta": {
        "add_global_case_list": true,
        "cancer_study_identifier": "djerba_test_001",
        "citation": null,
        "description": "Test of Djerba software package (September 2020)",
        "groups": null,
        "name": "Djerba Test 001",
        "pmid": null,
        "reference_genome": null,
        "short_name": "Djerba 001",
        "tags_file": null,
        "type_of_cancer": "ductal carcinoma"
    }
}
